.github/workflows/_test-judge-control-app-release.yml
.github/workflows/_test-judge-control-app.yml
.github/workflows/_test-queue-app-release.yml
.github/workflows/_test-queue-app.yml
.github/workflows/release.yml

これまでのdead_codeも検出するCIはrelease用にして、develop用のCIではdead_codeを許すように変更
close #18

開発中はdead_codeを許容

---

.env.dev

- close #44
docsのAPI versionを更新
- .end.devの`TRAO_DOCS_API_VERSION`を1.0.1に変更
- - [x] テストが不要な変更である

⬆️ api version 1.0.1

---

judge-control-app/generate-api-crate.sh

- close #10
judge-control-app向けのopenapi generator用シェルスクリプト
- 概要に同じ

✨ add sh for openapi generator

---

judge-control-app/src/models.rs
judge-control-app/src/models/judge_result.rs

- close #48
#50 と同じ
- 変更点1
- 変更点2
- 変更点3
- - [x] テストが不要な変更である

✨ judge result

---

src/container.rs
src/custom_rc.rs
src/custom_rc/entity.rs
src/custom_rc/entity/file_entity.rs
src/custom_rc/entity/writable_entity_factory.rs
src/custom_rc/file_factory.rs
src/custom_rc/writable_file.rs
src/submission_logic/file_preparation.rs
src/submission_logic/logic.rs
src/submission_logic/single_run.rs

- close #80
- writeable -> writable

✏️ fixed typo

---

.github/workflows/label-checker.yml

- close #109
CIにoutdatedラベルを追加
- 変更点1
- 変更点2
- 変更点3

💚 add outdated to label checker ci

---

judge_core/src/job.rs
judge_core/src/procedure.rs
judge_core/src/runner.rs
traopy/example/problems/addition/judge_procedure_sample.json
traopy/example/problems/addition/main.ipynb
traopy/python/traopy/lowlevel.pyi
traopy/src/lib.rs
traopy/src/models.rs
traopy/src/models/resource_kind.rs
traopy/src/models/runtime_text.rs

- close #111
<!—
なぜこの変更をするのかなど、概要を記載
—>
- 変更点1
- 変更点2
- 変更点3

🚚 onetime -> runtime

---

Cargo.toml
lib/grpc_schema/Cargo.toml
lib/grpc_schema/build.rs
lib/jobapi/Cargo.toml

- close #116
現在使われていない依存関係を削除
- 変更点1
- 変更点2
- 変更点3

➖ remove unused dependencies

---

lib/judge_core/src/common.rs
lib/judge_core/src/job.rs
lib/judge_core/src/lib.rs
lib/judge_core/src/problem_registry.rs
lib/judge_core/src/runner.rs
lib/local_jobapi/Cargo.toml
lib/local_jobapi/src/job_outcome.rs
lib/local_jobapi/src/jobapi.rs
lib/local_jobapi/src/lib.rs

- close #120
作問、デバッグ用
- 変更点1
- 変更点2
- 変更点3

✨ job api for local environment

---

lib/judge_core/src/problem_registry.rs
lib/judge_core/src/writer_schema_transpiler.rs
lib/local_problem_registry/src/lib.rs
lib/local_problem_registry/src/registry_server.rs

- close #125
- 変更点1
- 変更点2
- 変更点3

✨ depId->name

---

.github/workflows/python.yml

- close #115
pythonライブラリ向けのCIを追加

👷 python library buildcheck ci

---

pylib/traopy/python/traopy/lowlevel.pyi
pylib/traopy/src/local_judge.rs
pylib/traopy/src/models/dependency.rs
pylib/traopy/src/models/empty_directory.rs
pylib/traopy/src/models/execution.rs
pylib/traopy/src/models/output.rs
pylib/traopy/src/models/resource_kind.rs
pylib/traopy/src/models/runtime_text.rs
pylib/traopy/src/models/text.rs
pylib/traopy/src/procedure_builder.rs

- close #145
traopyのdocstringを書いた

📝 add docs for traopy

---

lib/judge_core/src/problem_registry.rs
lib/local_problem_registry/src/registry_server.rs
lib/problem_registry/src/server.rs

🐛 fix remove fn

---

lib/judge_core/src/has_cycle.rs
lib/judge_core/src/lib.rs

- close #161
与えられたグラフが巡回するサイクルを持っているか判別する
- 変更点1
- 変更点2
- 変更点3

Add func Has_Cycle

---

lib/judge_core/src/judge_output.rs
lib/judge_core/src/runner.rs

- close  #177
可読性が終わっているため
- 変更点1
- 変更点2
- 変更点3

🎨 improve heavy nest of judge_output enums

---

lib/jobapi/Cargo.toml
lib/jobapi/src/jobapi.rs
lib/judge_core/Cargo.toml
lib/judge_core/src/job.rs
lib/judge_core/src/problem_registry.rs
lib/local_jobapi/Cargo.toml
lib/local_jobapi/src/jobapi.rs
lib/local_problem_registry/Cargo.toml
lib/local_problem_registry/src/registry_client.rs
lib/local_problem_registry/src/registry_server.rs
lib/problem_registry/Cargo.toml
lib/problem_registry/src/client.rs
lib/problem_registry/src/server.rs

- close #175
バックエンド部分との統一と可読性改善のため、trait内のimpl Future...をasync_traitに変更
- 変更点1
- 変更点2
- 変更点3

🎨 replace impl Future<... to async_trait

---

lib/judge_core/src/model/identifiers.rs

- close #184
uuid <-> resourceId, depId, runtimeIdの変換を導入

✨ id and uuid conversion

---

lib/judge_core/src/model.rs
lib/judge_core/src/model/judge.rs

- close #192 
back-judgeのインターフェースをtraitとして追加

✨ judge api trait

---

.gitmodules

- close #205
gRPCスキーマをjudgeに移動したため

⚰️ remove unused submodule

---

lib/judge_core/src/logic.rs
lib/judge_core/src/logic/problem_presets.rs
lib/judge_core/src/logic/problem_presets/normal_judge.rs

- close #217 
backend_appで使うので取り急ぎ

✨ normal judge preset(todo)

---

Cargo.toml
app/backend_app/Cargo.toml
app/judge_control_app/Cargo.toml
lib/back_judge_grpc/Cargo.toml
lib/backend_domain/Cargo.toml
lib/backend_infra/Cargo.toml
lib/backend_usecase/Cargo.toml
lib/jobapi/Cargo.toml
lib/judge_core/Cargo.toml
lib/judge_infra_mock/Cargo.toml
lib/problem_registry/Cargo.toml
pylib/traopy_builder/Cargo.toml
pylib/traopy_util/Cargo.toml

🎨 use same edition and version project-wide

---

lib/judge_core/src/constant.rs
pylib/traopy_util/src/v0.rs
pylib/traopy_util/src/v0/command.rs

✨ compile run in traopy_util

---

pylib/traopy_util/src/v0.rs
pylib/traopy_util/src/v0/judge_status.rs
pylib/traopy_util/src/v0/output.rs

✨ judge merge utility

---

Cargo.toml
lib/judge_core/src/logic/problem_presets/normal_judge.rs

- close #232
テストケースの名前の追加、
normal_problemからprecedureを作成する際のmemory,timeのlimitを追加
- 変更点1
- 変更点2
- 変更点3

add normal judge testcase name and limits

---

lib/judge_core/src/logic/writer_schema_registerer.rs
lib/judge_core/src/model/problem_registry.rs
lib/judge_infra_mock/src/multi_proc_problem_registry/registry_server.rs
lib/judge_infra_mock/src/one_proc_problem_registry.rs
lib/judge_infra_mock/src/one_proc_problem_registry/registry_server.rs
lib/problem_registry/src/server.rs
pylib/traopy_builder/src/local_judge.rs

- close #241
dep name repoの導入に伴って

🔥 delete depId related features of problem registry

---

lib/judge_core/src/logic.rs
lib/judge_core/src/logic/registered_procedure_remover.rs

✨ add wrapper of testcase removal

---

pylib/traopy_util/src/v0/exec_with_stats.rs

maxrss is in byte in macos

---

.github/workflows/traopy-util-release.yml

あまり良くないけどworkflowへの変更を戻す必要があるため

Release traopy util

---

pylib/traopy_util/pyproject.toml

🚀 change traopy util version 0.1.0 -> 0.1.1

---

app/judge_control_app/Cargo.toml
app/judge_control_app/src/bin/main.rs

✨ add judge control app for deployment

---

lib/problem_registry/src/client.rs

fix/#283 Correct S3 API usage

---

lib/jobapi/src/actor/file_factory.rs
lib/jobapi/src/jobapi.rs

Reverts traP-jp/traO-Judge-judge#292

Revert "FileFactory has Uuid"

---

lib/jobapi/src/actor/file_factory.rs

ignore ErrorKind::AlreadyExists

---

.github/workflows/build-judge-control-app.yml
lib/problem_registry/src/client.rs

- close #309
S3からのダウンロード時、next()を忘れていて内容の読み込みに失敗していた

Fix/#309 fix-s3-download

---

lib/jobapi/src/aws.rs

- close #302
user_data.shをinclude_bytes!()で読み込み

Fix #302 user_data.sh

---

lib/jobapi/src/aws.rs

- close #314
subnet-idを今まで設定していなかったが、環境変数から読み込むように変更した

use subnet id from env

---

Cargo.toml
lib/jobapi/Cargo.toml
lib/jobapi/src/aws.rs
lib/jobapi/src/grpc.rs

close #318
- `[workspace.dependencies]` を使いました
- 依存関係を少し見直しました
- 機能に変更はありません

[workspace.dependencies] を使う

---

lib/jobapi/assets/user_data.sh

rename exec-http-server to exec-app

---

lib/jobapi/src/grpc.rs

#327 
- 処理の変更
- 受け取ったレスポンスのデバッグ出力
を入れました（直るか不明、いったんログを見たい）．

gRPC のレスポンス受け取り時の処理が間違っている

---

lib/jobapi/src/aws.rs

increase ebs size to 32 GiB (from 8)

---

lib/jobapi/src/aws.rs

fix InvalidBlockDeviceMapping error

---

lib/jobapi/src/grpc.rs

インスタンス起動待ち時間延ばす

---

.github/workflows/build-exec-app.yml
.github/workflows/build-judge-control-app.yml

split cache

---

lib/judge_core/Cargo.toml
lib/judge_core/src/logic/runner.rs

📈 tracing for runner

---

lib/jobapi/src/aws.rs

fix build error caused by #340

---

app/exec_app/Cargo.toml
app/exec_app/src/main.rs

mkdir and add log

---

Cargo.lock
app/exec_app/src/main.rs

Fix/#348 exec-app outcome path

---

lib/backend_usecase/src/service/user.rs

fix: update icon URL handling in user update

---

app/judge_control_app/src/bin/main.rs
app/judge_control_app/src/bin/mock.rs
lib/back_judge_grpc/src/client.rs
lib/back_judge_grpc/src/server.rs
lib/judge_core/src/logic.rs
lib/judge_core/src/logic/judge_service_impl.rs
lib/judge_core/src/model/judge.rs
pylib/traopy_builder/src/builder.rs

🚚 judgeapi -> judgeService

---

lib/jobapi/src/jobapi.rs

close #351
いったん environment variable not found のエラーは消えるはず

dependencies に追加で `OUTPUT_PATH` を送る

---

lib/jobapi/src/aws.rs

- close #391
その機能を `ProblemRegistryClient::fetch` に移行させたため、ここでは不要

refactor: remove unused `place_file`

---

Cargo.toml
app/backend_app/src/handler.rs
app/backend_app/src/handler/auth.rs
app/backend_app/src/handler/editorial.rs
app/backend_app/src/handler/problems.rs
app/backend_app/src/handler/submissions.rs
app/backend_app/src/handler/testcase.rs
app/backend_app/src/handler/users.rs
app/backend_app/tests/users/common/check.rs
app/backend_app/tests/users/common/mod.rs
app/backend_app/tests/users/put_users.rs
app/exec_app/src/main.rs
lib/backend_domain/src/model/rules_test.rs
lib/backend_infra/src/external/mail.rs
lib/backend_infra/src/model/uuid.rs
lib/backend_infra/src/provider.rs
lib/backend_usecase/src/service/auth.rs
lib/backend_usecase/src/service/testcase.rs
lib/backend_usecase/src/service/user.rs
lib/jobapi/src/actor/instance_pool.rs
lib/jobapi/src/aws.rs
lib/jobapi/src/grpc.rs
lib/jobapi/src/jobapi.rs
lib/judge_core/src/logic/judge_service_impl.rs
lib/judge_core/src/logic/runner.rs
lib/judge_core/src/logic/validation/has_cycle.rs
lib/judge_infra_mock/src/jobapi/jobapi.rs
lib/problem_registry/src/client.rs
pylib/traopy_util/src/v0/exec_with_stats.rs

feat: update edition to 2024

---

.devcontainer/Dockerfile
.devcontainer/compose.yaml
.devcontainer/devcontainer.json

🧑‍💻 add devcontainer

---

app/backend_app/src/handler/submissions.rs
lib/backend_usecase/src/service/submission.rs

- close #413 
get submission、get submissionsの引数をoption<string>からoption<&str>に変えました。

option<string>からoption<&str>に変えた

---

lib/problem_registry/src/client.rs
lib/problem_registry/src/server.rs

- close #424
- S3 への put, delete の実装をした
- put のときの invalid schema 等の判定がまだ

S3 の PutObject, DeleteObject の実装

---

app/backend_app/src/model/users.rs
app/backend_app/tests/users/common/check.rs

changed UserResponse's display_id to id and changed it String

---

lib/backend_usecase/src/service.rs
lib/backend_usecase/src/service/auth.rs
lib/backend_usecase/src/service/auth_mail_template.rs

- close #441 
mail の文面を作る部分を分けた
なんか違う気がするのでいい方法教えて

add authentication mail template provider and update auth service
